######################################################################
# Automatically generated by qmake (3.0) ?? 11? 30 09:55:49 2017
######################################################################

TEMPLATE = subdirs

SUBDIRS += \
           deepin-font-installer\
           libdeepin-font-installer\

deepin-font-installer.depends = libdeepin-font-installer
